clinicaVeterinaria/Controllers/AnimalController.cs
using clinicaVeterinaria.Dados;
using clinicaVeterinaria.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace clinicaVeterinaria.Controllers
{
    public class AnimalController : Controller
    {
        AnimalAcoes animalAcoes = new AnimalAcoes();

        public void CarregaTipoAnimais()
        {
            List<SelectListItem> ag = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=db_veterinaria;User=root;pwd=root"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tipoAnimal;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    ag.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();
                con.Open();
            }


            ViewBag.tipoAnimal = new SelectList(ag, "Value", "Text");
        }

        public void CarregaClientes()
        {
            List<SelectListItem> ag = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=db_veterinaria;User=root;pwd=root"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from cliente;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    ag.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();
                con.Open();
            }


            ViewBag.cliente = new SelectList(ag, "Value", "Text");
        }

        public ActionResult CreateAnimal() //Carrega a página de cadastro do Tipo
        {
            if (string.IsNullOrEmpty(Session["usu"]?.ToString()) || Session["tipo"]?.ToString() != "1")
            {
                return RedirectToAction("Index", "Home");
            }
            CarregaClientes();
            CarregaTipoAnimais();
            return View();
        }

        [HttpPost]
        public ActionResult CreateAnimal(AnimalModel animal) //Efetua o cadastro
        {
            CarregaClientes();
            CarregaTipoAnimais();

            animal.IdCliente =  int.Parse(Request["cliente"]);
            animal.IdTipo =  int.Parse(Request["tipoAnimal"]);

            animalAcoes.inserirAnimal(animal);
            Response.Write("<script>alert('Cadastro realizado com sucesso')</script>");
            return View();
        }

        public ActionResult GetAnimais()
        {
            if (string.IsNullOrEmpty(Session["usu"]?.ToString()))
            {
                return RedirectToAction("Index", "Home");
            }
            GridView dgv = new GridView();
            dgv.DataSource = animalAcoes.ConsultaAnimal();
            dgv.DataBind();
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            dgv.RenderControl(htw);
            ViewBag.GridViewString = sw.ToString();
            return View();
        }
    }
}

clinicaVeterinaria/Controllers/ClienteController.cs
using clinicaVeterinaria.Dados;
using clinicaVeterinaria.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace clinicaVeterinaria.Controllers
{
    public class ClienteController : Controller
    {
        ClienteAcoes clienteAcoes = new ClienteAcoes();

        public ActionResult CreateCliente() //Carrega a página de cadastro do Tipo
        {
            if (string.IsNullOrEmpty(Session["usu"]?.ToString()) || Session["tipo"]?.ToString() != "1")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult CreateCliente(ClienteModel cliente) //Efetua o cadastro
        {
            clienteAcoes.inserirCliente(cliente);
            Response.Write("<script>alert('Cadastro realizado com sucesso')</script>");
            return View();
        }

        public ActionResult GetClientes()
        {
            if (string.IsNullOrEmpty(Session["usu"]?.ToString()))
            {
                return RedirectToAction("Index", "Home");
            }
            GridView dgv = new GridView();
            dgv.DataSource = clienteAcoes.ConsultaCliente();
            dgv.DataBind();
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            dgv.RenderControl(htw);
            ViewBag.GridViewString = sw.ToString();
            return View();
        }
    }
}

clinicaVeterinaria/Controllers/HomeController.cs
using clinicaVeterinaria.Dados;
using clinicaVeterinaria.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace clinicaVeterinaria.Controllers
{
    public class HomeController : Controller
    {
        LoginAcoes acoesLogin = new LoginAcoes();

        public ActionResult Index()
        {
            if (!string.IsNullOrEmpty(Session["usu"]?.ToString())) RedirectToAction("Menu");
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoginModel login) //Realiza o teste de login, direcionando para o About ou novamente para o login com a mensagem de erro
        {
            acoesLogin.TestarUsuario(login);

            if (login.Usuario != null)
            {
                FormsAuthentication.SetAuthCookie(login.Usuario, false);
                Session["usu"] = login.Usuario;
                Session["tipo"] = login.IdTipoUsuario;

                return RedirectToAction("Menu", "Home");
            }
            else
            {
                ViewBag.msgLogar = "Usuário e/ou senha incorreto(s)";
                return View();
            }
        }

        public ActionResult Menu()
        {
            if(string.IsNullOrEmpty(Session["usu"]?.ToString()))
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Sair()
        {
            if (string.IsNullOrEmpty(Session["usu"]?.ToString()))
            {
                Session["usu"] = null;
                Session["tipo"] = null;
            }
            return RedirectToAction("Index");
        }

    }
}

clinicaVeterinaria/Controllers/TipoAnimalController.cs
using clinicaVeterinaria.Dados;
using clinicaVeterinaria.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace clinicaVeterinaria.Controllers
{
    public class TipoAnimalController : Controller
    {
        TipoAnimalAcoes tipoAnimalAcoes = new TipoAnimalAcoes();

        public ActionResult CreateTipoAnimal() //Carrega a página de cadastro do Tipo
        {
            if (string.IsNullOrEmpty(Session["usu"]?.ToString()) || Session["tipo"]?.ToString() != "1")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult CreateTipoAnimal(TipoAnimalModel tipoAnimal) //Efetua o cadastro
        {
            tipoAnimalAcoes.inserirTipoAnimal(tipoAnimal);
            Response.Write("<script>alert('Cadastro realizado com sucesso')</script>");
            return View();
        }

        public ActionResult GetTipoAnimais()
        {
            if (string.IsNullOrEmpty(Session["usu"]?.ToString()))
            {
                return RedirectToAction("Index", "Home");
            }
            GridView dgv = new GridView();
            dgv.DataSource = tipoAnimalAcoes.ConsultaTipoAnimal();
            dgv.DataBind();
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            dgv.RenderControl(htw);
            ViewBag.GridViewString = sw.ToString();
            return View();
        }
    }
}

clinicaVeterinaria/Controllers/UsuarioController.cs
using clinicaVeterinaria.Dados;
using clinicaVeterinaria.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace clinicaVeterinaria.Controllers
{
    public class UsuarioController : Controller
    {
        LoginAcoes acoesLogin = new LoginAcoes();

        public void CarregaUsuario()
        {
            List<SelectListItem> usu = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=db_veterinaria;User=root;pwd=root"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tipoUsuario;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    usu.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();
                con.Open();
            }


            ViewBag.tipo = new SelectList(usu, "Value", "Text");
        }

        public ActionResult CadLogin() //Carrega a página de cadastro do Login
        {
            if (Session["usu"] != null && Session["tipo"].ToString() == "1")
            {
                CarregaUsuario();
                return View();
            }
            else
            {
                return RedirectToAction("Menu", "Home");
            }
        }
        [HttpPost]
        public ActionResult CadLogin(LoginModel cmLogin) //Efetua o cadastro do Login
        {
            CarregaUsuario();
            if (cmLogin.Senha == cmLogin.ConfirmarSenha)
            {
                var tipo = Request["tipo"];
                cmLogin.IdTipoUsuario = int.Parse(tipo);
                acoesLogin.inserirLogin(cmLogin);
                Response.Write("<script>alert('Cadastro realizado com sucesso')</script>");
            }
            else
            {
                Response.Write("<script>alert('Senhas nao conferem')</script>");
            }
            return View();

        }

        public ActionResult GetUsuarios()
        {
            if (string.IsNullOrEmpty(Session["usu"]?.ToString()))
            {
                return RedirectToAction("Index", "Home");
            }
            GridView dgv = new GridView();
            dgv.DataSource = acoesLogin.ConsultaUsuarios();
            dgv.DataBind();
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            dgv.RenderControl(htw);
            ViewBag.GridViewString = sw.ToString();
            return View();
        }
    }
}

clinicaVeterinaria/Views/Home/Index.cshtml
@model clinicaVeterinaria.Models.LoginModel
@{
    ViewBag.Title = "Home Page";
}

@ViewBag.confCadastro


@using (Html.BeginForm("Index", "Home", FormMethod.Post))
{
    <fieldset>
        <br />
        <h2>Entrar</h2>
        <br />
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i style="font-size:20px;" class="fas fa-envelope"></i></span>

                @Html.EditorFor(x => x.Usuario, new
           {
               htmlAttributes = new { id = "txtUsuario", senha = "txtUsuario", type = "text", @class = "form-control", placeholder = "Digite o usuario", required = "required", maxlength = "30" }
           })

                @Html.ValidationMessageFor(x => x.Usuario, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><i style="font-size:20px;" class="fas fa-lock"></i></span>

                @Html.EditorFor(x => x.Senha, new
           {
               htmlAttributes = new { id = "txtSenha", senha = "txtSenha", type = "password", @class = "form-control", placeholder = "Digite sua senha", required = "required", maxlength = "10" }
           })

                @Html.ValidationMessageFor(x => x.Senha, "", new { @class = "text-danger" })

            </div>
        </div>

        <input type="submit" class="button button-a button-big button-rouded" value="ENTRAR"><br />
        <br />

    </fieldset>
}

@ViewBag.msgLogar

clinicaVeterinaria/Views/Home/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}

<style>
    body{
        box-sizing: border-box;
    }

    .links {
        display: flex;
        flex-wrap: wrap;
    }

    .links > div {
        width: 23%;
        padding: 0 50px;
        margin: 1%;
        display: flex;
        flex-direction: column;
        align-items: center;
        font-size: 20px;
        text-align: center;
        color: black;
        flex-shrink: 1;
    }

    .links > div:nth-child(4n) {
        margin-right: 0;
        padding: 0 0 0 100px;
    }

    .links > div:nth-child(4n+1) {
        margin-left: 0;
        padding: 0 100px 0 0;
    }

    .links > div > img {
        box-sizing: border-box;
        order: -1;
        margin-bottom: 24px;
        width: 100%;
    }

    .links > div > a {
        flex-grow: 1;
    }

</style>

<h2>Menu</h2>

<div class="links">
    @if (Session["tipo"].ToString() == "1")
    {
        <div>
            @Html.ActionLink("Cadastrar novo usuario", "CadLogin", "Usuario", null, new { @style = "color: black" })
            <img src="~/Content/imagens/user.png" />
        </div>
        <div>
            @Html.ActionLink("Cadastrar atendimento", "CreateAtendimento", "Atendimento", null, new { @style = "color: black" })
            <img src="~/Content/imagens/vacina.png" />
        </div>
        <div>
            @Html.ActionLink("Cadastrar tipo de animal", "CreateTipoAnimal", "TipoAnimal", null, new { @style = "color: black" })
            <img src="~/Content/imagens/trilha-animal.png" />
        </div>
        <div>
            @Html.ActionLink("Cadastrar tipo de usuario", "CreateTipoUsuario", "TipoUsuario", null, new { @style = "color: black" })
            <img src="~/Content/imagens/user.png" />
        </div>
        <div>
            @Html.ActionLink("Cadastrar cliente", "CreateCliente", "Cliente", null, new { @style = "color: black" })
            <img src="~/Content/imagens/user.png" />
        </div>
        <div>
            @Html.ActionLink("Cadastrar Pet", "CreateAnimal", "Animal", null, new { @style = "color: black" })
            <img src="~/Content/imagens/trilha-animal.png" />
        </div>
        <div>
            @Html.ActionLink("Cadastrar veterinario", "CreateVeterinario", "Veterinario", null, new { @style = "color: black" })
            <img src="~/Content/imagens/veterinario.png" />
        </div>
    }

    <div>
        @Html.ActionLink("Consultar atendimento", "GetAtendimentos", "Atendimento", null, new { @style = "color: black" })
        <img src="~/Content/imagens/vacina.png" />
    </div>
    <div>
        @Html.ActionLink("Consultar tipo de animal", "GetTipoAnimais", "TipoAnimal", null, new { @style = "color: black" })
        <img src="~/Content/imagens/trilha-animal.png" />
    </div>
    <div>
        @Html.ActionLink("Consultar tipo de usuario", "GetTipoUsuarios", "TipoUsuario", null, new { @style = "color: black" })
        <img src="~/Content/imagens/user.png" />
    </div>
    <div>
        @Html.ActionLink("Consultar cliente", "GetClientes", "Cliente", null, new { @style = "color: black" })
        <img src="~/Content/imagens/user.png" />
    </div>
    <div>
        @Html.ActionLink("Consultar veterinario", "GetVeterinarios", "Veterinario", null, new { @style = "color: black" })
        <img src="~/Content/imagens/veterinario.png" />
    </div>
    <div>
        @Html.ActionLink("Consultar usuarios", "GetUsuarios", "Usuario", null, new { @style = "color: black" })
        <img src="~/Content/imagens/user.png" />
    </div>
    <div>
        @Html.ActionLink("Consultar animais", "GetAnimais", "Animal", null, new { @style = "color: black" })
        <img src="~/Content/imagens/trilha-animal.png" />
    </div>
</div>